### ISSUE TITLE
XmppDateTime crashes when parsing date

### ISSUE THREAD

**Issue by vanitasvitae** [igniterealtime/jxmpp#12]
Hi!
XmppDateTime.parseXEP0082Date(string) crashes for dates that should be valid according to XEP-0234 §5.

In a specific case, the method crashes when parsing the date "2017-07-11T18:31:34", which follows the example in 0234 §5. I couldn't figure out what is causing this so far.

```
java.text.ParseException: Unparseable date: "2017-07-11T18:31:34"
    at java.text.DateFormat.parse(DateFormat.java:366)
    at
org.jxmpp.util.XmppDateTime$DateFormatType.parse(XmppDateTime.java:117)
    at
org.jxmpp.util.XmppDateTime$DateFormatType.access$100(XmppDateTime.java:65)
    at org.jxmpp.util.XmppDateTime.parseXEP0082Date(XmppDateTime.java:159)
```

**Comment by Flowdalic** [comment]
I don't think it follows xep82 as the TZD part is missing.

**Comment by vanitasvitae** [comment]
So you think XEP-0234 (Jingle File Transfer) is defective?

**Comment by Flowdalic** [comment]
> So you think XEP-0234 (Jingle File Transfer) is defective?

Appears so.
