### ISSUE TITLE
XmlSplitter: Does not support XML Declarations

### ISSUE THREAD

**Issue by seamlik** [igniterealtime/jxmpp#13]
When the receiving XML stream contains an XML Declaration at the very beginning, `XmlSplitter` simply throws an `UnsupportedOperationException`.

RFC 6120 § 11.5 states that "Before sending a stream header, an implementation SHOULD send an XML declaration". And ejabberd clearly sends XML declarations.

**Comment by Flowdalic** [comment]
Thanks for reporting. A test vector and a stacktrace would be nice.

**Comment by seamlik** [comment]
Hmm, you will understand it just from [here](https://github.com/igniterealtime/jxmpp/blob/3b78374f380863da2278a63258e9c6ca9e5789ef/jxmpp-core/src/main/java/org/jxmpp/xml/splitter/XmlSplitter.java#L252).

**Comment by Flowdalic** [comment]
Fixed with https://github.com/igniterealtime/jxmpp/commit/4e4a79446dfd5b1dd700d27f71e972c559c691fe
