### ISSUE TITLE
Version 1.0.1 isn't tagged

### ISSUE THREAD

**Issue by robmv** [igniterealtime/jxmpp#27]
1.0.1 shows on maven central under https://search.maven.org/artifact/org.jxmpp/jxmpp-core/1.0.1/jar but the source code isn't tagged on this repository. At the same time the maven pom it is pointing to https://github.com/igniterealtime/Smack as the SCM URL

**Comment by Flowdalic** [comment]
Thanks for reporting. Pushed the 1.0.1 tag.
