### ISSUE TITLE
Could not find jxmpp-jid-tests.jar 

### ISSUE THREAD

**Issue by bangarharshit** [igniterealtime/jxmpp#7]
While setting smack for a fix  I am getting this issue with gradle eclipse. I am using master. Since there is no way to report issue on smack so thought of putting here.

These are the files in m2 repository

jxmpp-jid-0.5.0-alpha1.jar       jxmpp-jid-0.5.0-alpha1.pom       _remote.repositories             
jxmpp-jid-0.5.0-alpha1.jar.sha1  jxmpp-jid-0.5.0-alpha1.pom.sha1

**Comment by guusdk** [comment]
Really? https://github.com/igniterealtime/Smack#bug-reporting

**Comment by bangarharshit** [comment]
Sorry. My mistake closing.

**Comment by bangarharshit** [comment]
I am opening an issue on forum as mentioned in the doc
